### NUMPY BASICS
```bash
pip install numpy
```


In [1]:
import numpy as np

### 1ST SAMPLE IN NUMPY (with regular python list)

In [ ]:
#regular python list
numbers = [1, 2, 3]
result = [x + 2 for x in numbers]
print(result)

[3, 4, 5]


In [19]:
import numpy as np

array_a = np.array([1, 2, 3])
result = array_a + 2
print(result)

[3 4 5]


### Creating a NumPy Array

In [1]:
import numpy as np

array_1 = np.array([1, 2, 3])  
array_2 = np.array([[1, 2, 3], 
[4, 5, 6]]) 

print("1D Array:", array_1)
print("2D Array:\n", array_2)

1D Array: [1 2 3]
2D Array:
 [[1 2 3]
 [4 5 6]]


### Accessing Elements

In [2]:
import numpy as np

array = np.array([[10, 20, 30], 
                 [40, 50, 60]])
print(array[0, 1]) 

20


### Adding Arrays – np.concatenate()


In [3]:
import numpy as np

a = np.array([[1, 2], 
[3, 4]])
b = np.array([[5, 6]])

result = np.concatenate((a, b), axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]]


### Sorting Arrays – np.sort()


In [4]:
import numpy as np

arr = np.array([[3, 1, 2], 
[9, 7, 8]])
sorted_arr = np.sort(arr)
print(sorted_arr) 

[[1 2 3]
 [7 8 9]]


### Removing Elements in NumPy


In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40])
new_arr = np.delete(arr, 2) 

print(new_arr) 

[10 20 40]


### Broadcasting in numpy

In [6]:
import numpy as np

arr_a = np.array([1, 2, 3])       
arr_b = 10 

result = arr_a + arr_b 

print("Result:", result)

Result: [11 12 13]


### Basic Array Operations

1. Element wise Arithmetic

In [9]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b) 
print(a * b)
print(a / b)
print(a - b)
print(a ** b)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[-3 -3 -3]
[  1  32 729]


2. Comparison Operations & Logical Operations


In [10]:
import numpy as np

a = np.array([1, 2, 3])
print(a > 2)

[False False  True]


2.1 Logical Operations


In [11]:
import numpy as np

a = np.array([True, False, True])
b = np.array([False, False, True])

print(np.logical_and(a, b))

[False False  True]


3. Matrix Multiplication

In [12]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

result = a @ b  # or np.dot(a, b)
print(result)

[[19 22]
 [43 50]]


4. In-Place Operations

In [13]:
import numpy as np

a = np.array([1, 2, 3])
a += 5
print(a)

[6 7 8]
